server.port=8082
spring.application.name=transaction-service

# PostgreSQL (Neon ? shared DB)
spring.datasource.url=jdbc:postgresql://ep-old-math-adge0cdl-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5jW6sBquEpcm
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=https://e-banking-3-0.onrender.com/
