spring.application.name=audit-service
server.port=8089

# PostgreSQL (Neon ? shared DB)
spring.datasource.url=jdbc:postgresql://ep-rapid-base-ah1999lk-pooler.c-3.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SA7hmuaRzyk4
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuration Eureka ESSENTIELLE
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Configuration instance (important)
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}



#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.auditservice.dto.AuditEvent
spring.kafka.consumer.auto-offset-reset=earliest



