server.port=8084
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://ep-rapid-base-ah1999lk-pooler.c-3.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SA7hmuaRzyk4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=https://e-banking-3-0.onrender.com/
