# --- Server Configuration ---
server.port=8084
spring.application.name=user-service

# --- Database Configuration (Neon Tech) ---
# Votre base de données PostgreSQL distante
spring.datasource.url=jdbc:postgresql://ep-rapid-base-ah1999lk-pooler.c-3.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SA7hmuaRzyk4
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Eureka Client (Service Discovery) ---
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- SECURITY CONFIGURATION (NOUVEAU - CRITIQUE) ---
# Ceci connecte le User-Service à Keycloak pour valider les tokens JWT.
# Quand un utilisateur arrive avec un token, Spring demande à Keycloak : "C'est valide ?"
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ebanking-realm

# (Optionnel) L'URL pour récupérer les clés publiques de signature
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ebanking-realm/protocol/openid-connect/certs

internal.secret=BankingSuperSecretKey_998877

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG