server.port=8081
spring.application.name=account-service

# PostgreSQL (Neon ? shared database)
spring.datasource.url=jdbc:postgresql://ep-rapid-base-ah1999lk-pooler.c-3.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_SA7hmuaRzyk4
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
