server.port=8080
spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# AJOUTÉ - Configuration pour Render
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port=80
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
