# Port standard pour Eureka
server.port=8761
spring.application.name=eureka-server

# Configuration pour que le serveur ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# --- Optimisations Cloud ---

# Permet au serveur de démarrer instantanément sans attendre ses pairs
eureka.server.wait-time-in-ms-when-sync-empty=0

# Important pour Render : évite d'utiliser les hostnames internes qui peuvent bugger
eureka.instance.prefer-ip-address=true

# Sécurité minimale : permet de voir l'interface Eureka sur Render
eureka.server.enable-self-preservation=false